name: bob-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - aicsimageio
  - bioformats_jar
  - scikit-image
  - pandas
  - seaborn
  - jupyterlab
  - matplotlib
  - scikit-learn
  - stackview
  - scipy
  - numpy
  - skan
  - pyclesperanto-prototype
  - pillow
  - anthropic
  - openai
  - pip:
    - bia-bob
    - pooch



  